[package]
name = "bitfield-rle"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/datrs/bitfield-rle"
documentation = "https://docs.rs/bitfield-rle"
description = "A run-length-encoder that compresses bitfields"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"

[dependencies]

[dev-dependencies]
# clippy = "0.0"
sparse-bitfield = { path = "../sparse-bitfield"}
